name: Deploy

on:
  push:
    branches:
    - dev
    - main
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json
      - name: Setup biome
        uses: biomejs/setup-biome@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Lint
        run: biome ci

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Typecheck
        run: bun typecheck
